name: test

on:
  pull_request:
    paths-ignore:
      - '**.md'
  push:
    branches:
      - master
    paths-ignore:
      - '**.md'

concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.ref }}

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: 'yarn'
          node-version: 16

      - run: |
          yarn install --frozen-lockfile --no-progress

      - run: |
          yarn run lint

  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          always-auth: true
          cache: 'yarn'
          node-version: 16

      - run: |
          yarn install --frozen-lockfile --no-progress

      - run: |
          yarn run test:ci

      - uses: actions/upload-artifact@v3
        if: github.ref == format('refs/heads/{0}', github.event.repository.default_branch)
        with:
          name: base-coverage-summary
          path: ./coverage/coverage-summary.json

      - uses: dawidd6/action-download-artifact@v2
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'pull_request'
        with:
          branch: ${{ github.event.repository.default_branch }}
          name: base-coverage-summary
          path: ./coverage/base
          workflow: test.yml

      - uses: adRise/jest-cov-reporter@main
        if: github.ref != format('refs/heads/{0}', github.event.repository.default_branch) && github.event_name == 'pull_request'
        with:
          base-coverage-report-path: ./coverage/base/coverage-summary.json
          branch-coverage-report-path: ./coverage/coverage-summary.json
          fullCoverageDiff: false
          useSameComment: true

      - uses: emibcn/badge-action@v1.2.1
        with:
          label: 'Coverage'
          path: '.github/badges/coverage.svg'
          status: '53.4%'
